### ISSUE TITLE
getting lot of errors

### ISSUE THREAD

**Issue by ncplus0** [AlexFolland/AutoGear#34]
im getting also a lot of errors i had to disable the addon
wow wrath AutoGear-2022-10-29-release-wrath.zip
im using a warrior

13326x AutoGear\AutoGear.lua:2690: attempt to index field '?' (a nil value) [string "@AutoGear\AutoGear.lua"]:2690: in function AutoGearConsiderItem'
[string "@AutoGear\AutoGear.lua"]:2498: in function AutoGearConsiderAllItems' [string "@AutoGear\AutoGear.lua"]:3852: in function AutoGearMain'
[string "@AutoGear\AutoGear.lua"]:331: in function <AutoGear\AutoGear.lua:330>

Locals:
info =

{
validGearSlots =
{
}
invType = 24
link = "|cffffffff|Hitem:2519::::::::28:::::::::|h[Heavy Shot]|h|r"
id = 2519
usable = 1
classID = 6
reason = "(found red text: "Bow")"
shouldShowScoreInTooltip = 1
rarityColor =
{
}
name = "Heavy Shot"
isGear = true
rarity = 1
subclassID = 3
equipped = false
item =
{
}
}
bag = 2
slot = 9
rollOn = nil
chooseReward = nil
justLook = nil
score = 0
firstValidGearSlot = 0
lowestScoringValidGearSlot = 0
(*temporary) = nil
(*temporary) =
{
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by AlexFolland** [comment]
I've pushed a release which ignores ammo.  Can you please try it and report back?

**Comment by ncplus0** [comment]
the bugs stopped, im gonna test with my others chars

**Comment by AutoGear** [comment]
I never use github really, so it was really surprising when i randomly got an email that I am now the name of a WoW addon and that I've been @ ed like 4 times within it.

I find it kinda funny not gonna lie.
![lmao](https://user-images.githubusercontent.com/43800328/198936169-3287b430-3cd9-4874-8d1e-5de24b86c95d.PNG)

**Comment by AlexFolland** [comment]
"Now"?  AutoGear the addon's been around for 13 years.  I guess github must have just recently implemented that feature.

**Comment by AutoGear** [comment]
Probably, I've only had github for maybe just over a year, but I've had the name for many more than that.
I'll just unsub the thread and leave you guys to it.
The only reason I left the comment was because I found it funny and thought you guys might as well.
See ya xd.

**Comment by AlexFolland** [comment]
It is a pretty funny name in the context of what the addon does.  It's also the name of my guild, since my brother and I use AutoGear while leveling.  It just sounds like you automatically roll on and equip gear upgrades.

**Comment by AlexFolland** [comment]
I've pushed a new release which should resolve several issues.  @ncplus0, would you mind giving it a try?

**Comment by furtrade** [comment]
I've been getting this since the last update. I really like the addon, I hope you get it up and running smooth without too much trouble 😆

1987x Interface/AddOns/AutoGear/AutoGear.lua:3410: bad argument #1 to 'find' (string expected, got nil)
[string "=[C]"]: in function `find'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:3410: in function `AutoGearGetPawnScaleName'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:3530: in function `AutoGearDetermineItemScore'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:2442: in function `AutoGearUpdateEquippedItems'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:3870: in function `AutoGearMain'
[string "@Interface/AddOns/AutoGear/AutoGear.lua"]:330: in function <Interface/AddOns/AutoGear/AutoGear.lua:329>

Locals:
(*temporary) = nil
(*temporary) = "Survival"
(*temporary) = "string expected, got nil"

**Comment by AlexFolland** [comment]
@furtrade Thanks for the detailed error message.  I've pushed a release which should solve that issue.  Please try it and let me know.

**Comment by AlexFolland** [comment]
The original issue this ticket tracks is solved, and the new issue should also be solved.  Therefore, I'm closing this one.  @furtrade If you see any further issues, please open a new ticket.  Thank you!
