### ISSUE TITLE
AutoGear replacing two-handed weapons with anything while playing Fury Warrior

### ISSUE THREAD

**Issue by yeetzy77** [AlexFolland/AutoGear#46]
Hello, I'm finding that AutoGear will equip items like Mining Pick to replace two-handed weapons. I think it might be due to the Titans Grip damage debuff?

Before Scan with slots locked:
![image](https://github.com/AlexFolland/AutoGear/assets/68456918/915d75e4-90aa-4aa6-9fe5-6557a75046ce)

After scan with slots unlocked:
![image](https://github.com/AlexFolland/AutoGear/assets/68456918/48191390-0ef7-4de0-bc67-56e66b162e77)

Gear Score:
![image](https://github.com/AlexFolland/AutoGear/assets/68456918/860772b2-546b-48a9-a7f1-aca294cc8db6)

I've made sure that AutoGear is set to the correct spec and tried force-spec, but no change. 
Not sure if I'm missing something or if this is infact a bug. I would love some advice please, cheers!

**Comment by AlexFolland** [comment]
Thanks for the report.  What version of the game client is this?  What version of AutoGear is running?

AutoGear checks whether the character can dual-wield 2-handers, and it looks like that check may not be passing for your character, since it says it won't equip that item.  Fury warrior has always been a bit tricky, and has worked on and off over the years as Blizzard has changed things.

In the mean time, it looks like the slot-locking mechanism is working to allow you to keep your chosen off-hand on, at least.  I know it sucks to see this issue though, so I would like to fix it if I get some time.

If you end up solving this by yourself or with someone's help, I would be glad to review and accept a pull request with the fix.

**Comment by AlexFolland** [comment]
I've pushed a potential fix, but tagged it for alpha and not release.  Would you mind testing it?

**Comment by AlexFolland** [comment]
OK, thank you for testing it.  It's impossible for me to test right now, so I made code changes with no testing, hoping it would work.  Since it didn't, I'd like to adjust my approach and fix it with testing.  However, to do that, I need a way to test it.

Would you be willing to chat in real time and resolve this together?  I'm thinking that you could share your screen and I could ask you to make particular code edits and reload your UI, or something like that.  If so, maybe we can chat via Google and coordinate that.  Feel free to message me via Google using my email address and we can discuss that further if you're interested.

**Comment by yeetzy77** [comment]
Yeah, I'd be more than happy to live test with you. I'll send you an email and we can organise a suitable time

**Comment by AlexFolland** [comment]
I think we resolved this together.  Thanks for your awesome cooperation!  If there are any cascading issues as a result of the fix, feel free to contact me any time!

**Comment by cdmichaelb** [comment]
@AlexFolland I'm getting this issue now, on multiple gear:
`[08:53:00] AutoGear: [Ripped Pants] (0.01) was determined to be better than [Neophyte's Pants] (0.00).  Would equip, but slot 7 is locked.
[08:53:00] AutoGear: [Soft Wool Boots] (0.01) was determined to be better than nothing (0.00).  Would equip, but slot 8 is locked.
[08:53:00] AutoGear: [Primitive Club] (0.02) was determined to be better than [Worn Mace] (0.01).  Would equip, but slot 16 is locked.`

**Comment by AlexFolland** [comment]
Thanks for the comment.  Can you confirm that slot-locking is disabled and/or that those slots are not configured to be locked?  If so, please do so in a new issue ticket, as that issue would not be related to this ticket's issue.
