### ISSUE TITLE
Can't set combat rogue pawnscale in WOTLK

### ISSUE THREAD

**Issue by tjesp** [AlexFolland/AutoGear#52]
If I type "/ag pawnscale rogue:combat" it says:

Autogear will now use "rogue:subtlety".

This happens even if i rename the scale to, say, "combat" and try to type "/ag pawnscale combat"

it still sets to subtlety.

**Comment by AlexFolland** [comment]
Can you please copy-paste the output of `/ag spec`?

**Comment by tjesp** [comment]
"None Rogue". I am below level 10 but intend to go combat. Is it not supposed to work that way below 10?

**Comment by AlexFolland** [comment]
Are you using a modified version of AutoGear that's different from the latest release from here?  That doesn't look like the output that AutoGear writes in the chat window when entering `/ag spec`.

**Comment by tjesp** [comment]
I am using the one from WowUp. It states same version as your site.

**Comment by AlexFolland** [comment]
OK, thanks for confirming.  The output looks very incomplete.  I guess it must have been a copy-paste error.  Can you please copy the full output?

**Comment by tjesp** [comment]
I don't know how to copy and paste from the chat window so here is a screenshot:

https://imgur.com/uWvQkwa

**Comment by AlexFolland** [comment]
OK, looks like you have Pawn disabled or not installed, so setting the Pawn scale doesn't matter.  It's using the internal weights right now.

**Comment by AlexFolland** [comment]
I've seen no response and it sounds like there may be no issue if Pawn is installed and Pawn usage is enabled, so I'm closing this.  Please feel free to comment with steps to reproduce, observed behavior, and expected behavior, and if the information describes an AutoGear issue, I will reopen this to maintain the context.

To be clear, I am interested in solving a problem, but without knowing the problem, I can't solve it.  Thank you for your initial report and correspondence.
