### ISSUE TITLE
Armor specialization in Cataclysm Classic

### ISSUE THREAD

**Issue by tjesp** [AlexFolland/AutoGear#67]
Does the addon take into consideration armor specialization bonuses? The reason I ask is because on my druid wearing full leather set I was equipped a cloth upgrade.

Perhaps the addon should insist on the correct gear specialization for the class, so for instance insist on leather for druids.

That is really not a big problem since the items you get as rewards are much better itemized in cataclysm.

**Comment by AlexFolland** [comment]
No, it doesn't.   I've considered whether it's necessary, and I don't think it is, considering the player can increase the value of armor in their Pawn scale if they want to.  It's kind of a micro-optimization and you can potentially lose more than 5% of your primary powerful stats by dismissing gear which would otherwise be a huge upgrade just to strictly maintain the armor specialization.  If someone wants to do that by valuing armor more, they already can.  What are your thoughts on that?

**Comment by AlexFolland** [comment]
I haven't heard anything for a while about this, so I will go with my rationale for now.  If you have further thoughts, please feel free to comment them here.
