### ISSUE TITLE
Shaman Weapon types

### ISSUE THREAD

**Issue by naviomg** [AlexFolland/AutoGear#69]
It seems there is an issue with Enhancement Shamans equipping 2h Weapons in Classic Sod(think it applies for other versions as well). I tried to overrule it via Pawn but the issue seems coming from autogear directly.
I think we are missing talent spellid(16269) in function AutoGearGetValidGearSlots(info)
![Autogear_ShamanWeaponTypes](https://github.com/user-attachments/assets/533852d3-aa30-4d43-ab6e-53389c433fe4)

**Comment by AlexFolland** [comment]
The weapons selection is from AutoGear's weighting table, so it can be overridden while using Pawn by using an AutoGear specialization override.  For example, if you pick arms warrior as a spec override (not Pawn scale override), it will equip 2-handers and not 1-handers.

That being said, these weapon usage types are opinions from other editions of WoW, where an enhancement shaman can equip a 2H but it's almost never a good idea to do so.  I've been considering separating the weapon usage type into its own selection so that it's clearer how it can be chosen.  Right now, it's tied directly into AutoGear weighting table and separating it out might be a good change to give the user a clearer way to control this.

**Comment by naviomg** [comment]
In sod both shamans are viable. It seems by using a diff spec override of arms or ret with a custom pawn profile does the trick.
